#!/bin/bash

function install {
    sudo cp "jepgo" /bin/
    sudo cp ".jepgo" /bin/ -r
}

function new_project {
    if [ -z "$1" ]; then
        echo "Error: Need a project name."
        return 1
    fi
    
    local project_name="$1"
    
    mkdir -p "$project_name"
    cp /bin/.jepgo/project/* -r "$project_name"
    echo "'$project_name' project created."
}

function new {
    if [ "$2" = "project" ]; then
        new_project "$3"
    else
        echo "Unknown command : jepgo new $2"
        return 1
    fi
}

if [ "$1" = "install" ]; then
    install
elif [ "$1" = "new" ]; then
    new "$@"
else
    echo "Unknown command"
    exit 1
fi
